sm8150-common: switch to armv8-2a
Solves the following error.
error: Incorrect TARGET_2ND_ARCH_VARIANT, armv8-a. Use armv8-2a instead..

Change-Id: I8784acc463d0bad7e99da3ad664537a2ec50857a